import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Headder from "@/components/common/headder";
import Footer from "@/components/common/footer";

const outfit = Outfit({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.className}  antialiased`}>
      <body className="min-h-full flex flex-col">
        <Headder/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
